// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 17.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Unsafe_space_travels.Desktop.Helper
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.IO;
    using Lemon.IO;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DirectoryListing : DirectoryListingBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n    <meta charset=\'utf-8\'>\r\n    <meta name=\"" +
                    "viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, use" +
                    "r-scalable=no\" />\r\n    <title>listing directory /</title>\r\n    <style>* {\r\n  mar" +
                    "gin: 0;\r\n  padding: 0;\r\n  outline: 0;\r\n}\r\n\r\nbody {\r\n  padding: 80px 100px;\r\n  fo" +
                    "nt: 13px \"Helvetica Neue\", \"Lucida Grande\", \"Arial\";\r\n  background: #ECE9E9 -web" +
                    "kit-gradient(linear, 0% 0%, 0% 100%, from(#fff), to(#ECE9E9));\r\n  background: #E" +
                    "CE9E9 -moz-linear-gradient(top, #fff, #ECE9E9);\r\n  background-repeat: no-repeat;" +
                    "\r\n  color: #555;\r\n  -webkit-font-smoothing: antialiased;\r\n}\r\nh1, h2, h3 {\r\n  fon" +
                    "t-size: 22px;\r\n  color: #343434;\r\n}\r\nh1 em, h2 em {\r\n  padding: 0 5px;\r\n  font-w" +
                    "eight: normal;\r\n}\r\nh1 {\r\n  font-size: 60px;\r\n}\r\nh2 {\r\n  margin-top: 10px;\r\n}\r\nh3" +
                    " {\r\n  margin: 5px 0 10px 0;\r\n  padding-bottom: 5px;\r\n  border-bottom: 1px solid " +
                    "#eee;\r\n  font-size: 18px;\r\n}\r\nul li {\r\n  list-style: none;\r\n}\r\nul li:hover {\r\n  " +
                    "cursor: pointer;\r\n  color: #2e2e2e;\r\n}\r\nul li .path {\r\n  padding-left: 5px;\r\n  f" +
                    "ont-weight: bold;\r\n}\r\nul li .line {\r\n  padding-right: 5px;\r\n  font-style: italic" +
                    ";\r\n}\r\nul li:first-child .path {\r\n  padding-left: 0;\r\n}\r\np {\r\n  line-height: 1.5;" +
                    "\r\n}\r\na {\r\n  color: #555;\r\n  text-decoration: none;\r\n}\r\na:hover {\r\n  color: #3030" +
                    "30;\r\n}\r\n#stacktrace {\r\n  margin-top: 15px;\r\n}\r\n.directory h1 {\r\n  margin-bottom:" +
                    " 15px;\r\n  font-size: 18px;\r\n}\r\nul#files {\r\n  width: 100%;\r\n  height: 100%;\r\n  ov" +
                    "erflow: hidden;\r\n}\r\nul#files li {\r\n  float: left;\r\n  width: 30%;\r\n  line-height:" +
                    " 25px;\r\n  margin: 1px;\r\n}\r\nul#files li a {\r\n  display: block;\r\n  height: 25px;\r\n" +
                    "  border: 1px solid transparent;\r\n  -webkit-border-radius: 5px;\r\n  -moz-border-r" +
                    "adius: 5px;\r\n  border-radius: 5px;\r\n  overflow: hidden;\r\n  white-space: nowrap;\r" +
                    "\n}\r\nul#files li a:focus,\r\nul#files li a:hover {\r\n  background: rgba(255,255,255," +
                    "0.65);\r\n  border: 1px solid #ececec;\r\n}\r\nul#files li a.highlight {\r\n  -webkit-tr" +
                    "ansition: background .4s ease-in-out;\r\n  background: #ffff4f;\r\n  border-color: #" +
                    "E9DC51;\r\n}\r\n#search {\r\n  display: block;\r\n  position: fixed;\r\n  top: 20px;\r\n  ri" +
                    "ght: 20px;\r\n  width: 90px;\r\n  -webkit-transition: width ease 0.2s, opacity ease " +
                    "0.4s;\r\n  -moz-transition: width ease 0.2s, opacity ease 0.4s;\r\n  -webkit-border-" +
                    "radius: 32px;\r\n  -moz-border-radius: 32px;\r\n  -webkit-box-shadow: inset 0px 0px " +
                    "3px rgba(0, 0, 0, 0.25), inset 0px 1px 3px rgba(0, 0, 0, 0.7), 0px 1px 0px rgba(" +
                    "255, 255, 255, 0.03);\r\n  -moz-box-shadow: inset 0px 0px 3px rgba(0, 0, 0, 0.25)," +
                    " inset 0px 1px 3px rgba(0, 0, 0, 0.7), 0px 1px 0px rgba(255, 255, 255, 0.03);\r\n " +
                    " -webkit-font-smoothing: antialiased;\r\n  text-align: left;\r\n  font: 13px \"Helvet" +
                    "ica Neue\", Arial, sans-serif;\r\n  padding: 4px 10px;\r\n  border: none;\r\n  backgrou" +
                    "nd: transparent;\r\n  margin-bottom: 0;\r\n  outline: none;\r\n  opacity: 0.7;\r\n  colo" +
                    "r: #888;\r\n}\r\n#search:focus {\r\n  width: 120px;\r\n  opacity: 1.0;\r\n}\r\n\r\n/*views*/\r\n" +
                    "#files span {\r\n  display: inline-block;\r\n  overflow: hidden;\r\n  text-overflow: e" +
                    "llipsis;\r\n  text-indent: 10px;\r\n}\r\n#files .name {\r\n  background-repeat: no-repea" +
                    "t;\r\n}\r\n#files .icon .name {\r\n  text-indent: 28px;\r\n}\r\n\r\n/*tiles*/\r\n.view-tiles ." +
                    "name {\r\n  width: 100%;\r\n  background-position: 8px 5px;\r\n}\r\n.view-tiles .size,\r\n" +
                    ".view-tiles .date {\r\n  display: none;\r\n}\r\n\r\n/*details*/\r\nul#files.view-details l" +
                    "i {\r\n  float: none;\r\n  display: block;\r\n  width: 90%;\r\n}\r\nul#files.view-details " +
                    "li.header {\r\n  height: 25px;\r\n  background: #000;\r\n  color: #fff;\r\n  font-weight" +
                    ": bold;\r\n}\r\n.view-details .header {\r\n  border-radius: 5px;\r\n}\r\n.view-details .na" +
                    "me {\r\n  width: 60%;\r\n  background-position: 8px 5px;\r\n}\r\n.view-details .size {\r\n" +
                    "  width: 10%;\r\n}\r\n.view-details .date {\r\n  width: 30%;\r\n}\r\n.view-details .size,\r" +
                    "\n.view-details .date {\r\n  text-align: right;\r\n  direction: rtl;\r\n}\r\n\r\n/*mobile*/" +
                    "\r\n@media (max-width: 768px) {\r\n  body {\r\n    font-size: 13px;\r\n    line-height: " +
                    "16px;\r\n    padding: 0;\r\n  }\r\n  #search {\r\n    position: static;\r\n    width: 100%" +
                    ";\r\n    font-size: 2em;\r\n    line-height: 1.8em;\r\n    text-indent: 10px;\r\n    bor" +
                    "der: 0;\r\n    border-radius: 0;\r\n    padding: 10px 0;\r\n    margin: 0;\r\n  }\r\n  #se" +
                    "arch:focus {\r\n    width: 100%;\r\n    border: 0;\r\n    opacity: 1;\r\n  }\r\n  .directo" +
                    "ry h1 {\r\n    font-size: 2em;\r\n    line-height: 1.5em;\r\n    color: #fff;\r\n    bac" +
                    "kground: #000;\r\n    padding: 15px 10px;\r\n    margin: 0;\r\n  }\r\n  ul#files {\r\n    " +
                    "border-top: 1px solid #cacaca;\r\n  }\r\n  ul#files li {\r\n    float: none;\r\n    widt" +
                    "h: auto !important;\r\n    display: block;\r\n    border-bottom: 1px solid #cacaca;\r" +
                    "\n    font-size: 2em;\r\n    line-height: 1.2em;\r\n    text-indent: 0;\r\n    margin: " +
                    "0;\r\n  }\r\n  ul#files li:nth-child(odd) {\r\n    background: #e0e0e0;\r\n  }\r\n  ul#fil" +
                    "es li a {\r\n    height: auto;\r\n    border: 0;\r\n    border-radius: 0;\r\n    padding" +
                    ": 15px 10px;\r\n  }\r\n  ul#files li a:focus,\r\n  ul#files li a:hover {\r\n    border: " +
                    "0;\r\n  }\r\n  #files .header,\r\n  #files .size,\r\n  #files .date {\r\n    display: none" +
                    " !important;\r\n  }\r\n  #files .name {\r\n    float: none;\r\n    display: inline-block" +
                    ";\r\n    width: 100%;\r\n    text-indent: 0;\r\n    background-position: 0 50%;\r\n  }\r\n" +
                    "  #files .icon .name {\r\n    text-indent: 41px;\r\n  }\r\n}\r\n#files .icon-directory ." +
                    "name {\r\n  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB" +
                    "AAAAAQCAMAAAAoLQ9TAAAABGdBTUEAALGPC/xhBQAAAWtQTFRFAAAA/PPQ9Nhc2q402qQ12qs2/PTX2p" +
                    "g12p81+/LM89NE9dto2q82+/fp2rM22qY39d6U+/bo2qo2/frx/vz32q812qs12qE279SU8c4w9NZP+/" +
                    "LK//367s9y7s925cp0/vzw9t92//342po2/vz25s1579B6+OSO2bQ0/v799NyT8tE79dld8Msm+OrC/v" +
                    "zx79KA2IYs7s6I9d6R4cJe9+OF/PLI/fry79OF/v30//328tWB89RJ8c9p8c0u9eCf//7+9txs6sts5M" +
                    "dr+++5+u2z/vrv+/fq6cFz8dBs8tA57cpq+OaU9uGs27Y8//799NdX/PbY9uB89unJ//z14sNf+emh+e" +
                    "mk+vDc+uys9+OL8dJy89NH+eic8tN5+OaV+OWR9N2n9dtl9t529+KF9+GB9Nue9NdU8tR/9t5y89qW9d" +
                    "pj89iO89eG/vvu2pQ12Y4z/vzy2Ict/vvv48dr/vzz4sNg///+2Igty3PqwQAAAAF0Uk5TAEDm2GYAAA" +
                    "CtSURBVBjTY2AgA2iYlJWVhfohBPg0yx38y92dS0pKVOVBAqIi6sb2vsWWpfrFeTI8QAEhYQEta28nCw" +
                    "M1OVleZqCAmKCEkUdwYWmhQnFeOStQgL9cySqkNNDHVJGbiY0FKCCuYuYSGRsV5KgjxcXIARRQNncNj0" +
                    "9JTgqw0ZbkZAcK5LuFJaRmZqfHeNnpSucDBQoiEtOycnIz4qI9bfUKQA6pKKqAgqIKQyK8BgAZ5yfODm" +
                    "nHrQAAAABJRU5ErkJggg==);\r\n}\r\n#files .icon-text-html .name {\r\n  background-image:" +
                    " url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBT" +
                    "UEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAHtSURBVDjLjZM9T" +
                    "9tQFIYpQ5eOMBKlW6eWIQipa8RfQKQghEAKqZgKFQgmFn5AWyVDCipVQZC2EqBWlEqdO2RCpAssQBRsx" +
                    "1+1ndix8wFvfW6wcUhQsfTI0j33PD7n+N4uAF2E+/S5RFwG/8Njl24/LyCIOI6j1+v1y0ajgU64cSSTy" +
                    "bdBSVAwSMmmacKyLB/DMKBpGkRRZBJBEJBKpXyJl/yABLTBtm1Uq1X2JsrlMnRdhyRJTFCpVEAfSafTT" +
                    "UlQoFs1luxBAkoolUqQZbmtJTYTT/AoHInOfpcwtVtkwcSBgrkDGYph+60oisIq4Xm+VfB0+U/P0Lvj3" +
                    "NwPGfHPTcHMvoyFXwpe7UmQtAqTUCU0D1VVbwTPVk5jY19Fe3ZfQny7CE51WJDXqpjeEUHr45ki9rIqa" +
                    "4dmQiJfMLItGEs/FcQ2ucbRmdnSYy5vYWyLx/w3EaMfLmBaDpMQvuDJ65PY8Dpnz3wpYmLtApzcrIAqm" +
                    "frEgdZH1grY/a36w6Xz0DKD8ES25/niYS6+wWE8mWfByY8cXmYEJFYLkHUHtVqNQcltAvoLD3v7o/FUH" +
                    "sNvzlnwxfsCEukC/ho3yUHaBN5Buo17Ojtyl+DqrnvQgUtfcC0ZcAdkUeA+ye7eMru9AUGIJPe4zh509" +
                    "UP/AAfNypi8oj/mAAAAAElFTkSuQmCC);\r\n}\r\n#files .icon-application-javascript .name " +
                    "{\r\n  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAA" +
                    "QCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXH" +
                    "JZTwAAAHdSURBVDjLjZNPaxNBGIdrLwURLznWgkcvIrQhRw9FGgy01IY0TVsQ0q6GFkT0kwjJId9AP4A" +
                    "HP4Q9FO2hJ7El2+yf7OzMbja7Sf0578QdNybFLjwszLu/Z2femZkDMEfI54FkRVL4Dw8l8zqXEawMBgM" +
                    "2HA6vR6MRZiHraDabH7KSrKBA4SAIEIahxvd9eJ6HbrerJKZpotVqaUkavkMC+iCKIsRxrN6EEAKMMVi" +
                    "WpQT9fh/0k3a7PZZkBUPmqXAKCSjAOYdt21NLUj1JBYW7C6vi6BC8vKWKQXUXQcNA5Nh6KY7jqJl0Op1" +
                    "JwY/Hi7mLp/lT/uoA/OX2WLC3C9FoQBwfILKulIRmQv1wXfevwHmyuMPXS5Fv1MHrFSTmhSomnUvw/Sp" +
                    "o3C+vg3/+pJZDPSGRFvilNV+8PUZvoziKvn+d3LZvJ/BelMDevIZXK2EQCiUhtMDM53bY5rOIGXtwjU3" +
                    "EVz/HM5Az8eplqPFKEfzLR91cOg8TPTgr3MudFx+d9owK7KMNVfQOtyQ1OO9qiHsWkiRRUHhKQLuwfH9" +
                    "+1XpfhVVfU0V3//k4zFwdzjIlSA/Sv8jTOZObBL9uugczuNaCP5K8bFBIhduE5bdC3d6MYIkkt7jOKXT" +
                    "1l34DkIu9e0agZjoAAAAASUVORK5CYII=);\r\n}\r\n#files .icon-map .name {\r\n  background-i" +
                    "mage: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA" +
                    "BGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAK2SURBVBgZ" +
                    "BcHLjxN1AADg79eZttvddttll+WxIGrAV4QYTbxoYsSLgjc5arx68qCGf8G7J+NBEg8e9GqURDEmEiOJ" +
                    "AWNUwIi8sryWDbSdmc60Mx2/Lxw78caZ1fXVo1EUAYAAACAIgICymrt/7/6P8er66tHPPzklNIJyPgNA" +
                    "ENRqAWSzBEFdN9TzWq3y0ckPj8ZRFKmUwuxL6fcXrJzJbJ18xFKv6/LlX1xMP3Nra6jXW3Z3eyiKm0Zp" +
                    "7t1jtWYcaQAMh9uGT7eMkkR2+m9JcluSJEJxQTEZm2Rj00liMkmUeSqEOYI4APr9ndQzi+/v4OPz2m+t" +
                    "Wd+zV2d2xaQ8pDfoaUUNcbMlyXIhFAgaQDAcDiXJ2MP1ymilNPn6X6q5OvvZrEhk49SsyBR5alpkQqhB" +
                    "DNDvr1PPDPrLhu89Y+XTbeUre7TXCo9MtzW7+y22I81W0zibYkSgQQB5XkiTzHA0NF6qPHiC/Iv/1FWu" +
                    "Mf1WPklMi1SeJubTVABBHACdzkB3OdVfXgbNtx/V+eCsuDpg7+pf8s7ERvcP7daW6eSaqPGOgDgAxsNU" +
                    "khRI/bZ5x41Zw66DlSdPXbZ5PLUr+kYx+slg8Yj2uW1hNRPQEIKA5cFuFgZ+z0rXpk2DwU53XjtgX7xi" +
                    "srXXoDuycX1B54dLbrQqdbMFYqjr2rmbV13YvKTb7cnzXJKkkqLw61MNh7+6Ijl/3eZK0+3nHzdqBvtb" +
                    "bRAHZGVqq5ppt7qWOn15MdVd6Or/ed2+W5lWkwfPHnbzsZZ2e8HStKCuQUwQQkPPsknItKuOxdC16+I9" +
                    "rc2Jqy8dURxMvHz2oX/27xa1m5irZqWAuCwrVVXZ2PGcjVUCCMIhvMpaCCC8OPdCNBMttESNSDWvlFUl" +
                    "vHni+Hc719dej5oxggAIAAAIAIGyrGzd3Tr9P5JrNp8Zt4rCAAAAAElFTkSuQmCC);\r\n}\r\n</style>\r" +
                    "\n  </head>\r\n  <body class=\"directory\">\r\n    <div id=\"wrapper\">\r\n      ");
            
            #line 288 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
 if(Parent.path != null) { 
            
            #line default
            #line hidden
            this.Write("      <h1><a href=\"");
            
            #line 289 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Parent.path));
            
            #line default
            #line hidden
            this.Write("\" class=\"icon icon-directory\" title=\"");
            
            #line 289 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Parent.name));
            
            #line default
            #line hidden
            this.Write("\">~</a>");
            
            #line 289 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Parent.name));
            
            #line default
            #line hidden
            this.Write("</h1>\r\n      ");
            
            #line 290 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
 }
            
            #line default
            #line hidden
            this.Write("      <ul id=\"files\" class=\"view-tiles\">\r\n      ");
            
            #line 292 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
 foreach(var folder in Folders) { 
            
            #line default
            #line hidden
            this.Write("         <li><a href=\"");
            
            #line 293 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(folder.path));
            
            #line default
            #line hidden
            this.Write("\" class=\"icon icon-directory\" title=\"");
            
            #line 293 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(folder.name));
            
            #line default
            #line hidden
            this.Write("\"><span class=\"name\">");
            
            #line 293 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(folder.name));
            
            #line default
            #line hidden
            this.Write("</span>");
            
            #line 293 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(folder.size));
            
            #line default
            #line hidden
            this.Write("<span class=\"size\"></span><span class=\"date\">");
            
            #line 293 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(folder.lastWriteTime.ToString("o")));
            
            #line default
            #line hidden
            this.Write("</span></a></li>\r\n      ");
            
            #line 294 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
 } 
            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 295 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
 foreach(var file in Files) { 
            
            #line default
            #line hidden
            this.Write("        <li><a href=\"");
            
            #line 296 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(file.path));
            
            #line default
            #line hidden
            this.Write("\" class=\"icon\" title=\"");
            
            #line 296 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(file.name));
            
            #line default
            #line hidden
            this.Write("\"><span class=\"name\">");
            
            #line 296 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(file.name));
            
            #line default
            #line hidden
            this.Write("</span><span class=\"size\">");
            
            #line 296 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(file.size));
            
            #line default
            #line hidden
            this.Write("</span><span class=\"date\">");
            
            #line 296 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(file.lastWriteTime.ToString("o")));
            
            #line default
            #line hidden
            this.Write("</span></a></li>\r\n      ");
            
            #line 297 "C:\Komachi\Development\Unsafe-space-travels.Desktop\Unsafe-space-travels.Desktop\Helper\DirectoryListing.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    </div>\r\n  </body>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class DirectoryListingBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
